/**
 * Fichier de constantes pour l'application de covoiturage
 * Contient tous les enums, rôles, permissions et statuts utilisés dans l'application
 */

// ========================================
// UTILISATEUR - CONSTANTES
// ========================================

const SEXE = {
  MASCULIN: 'M',
  FEMININ: 'F'
};

const TYPE_DOCUMENT_IDENTITE = {
  CNI: 'CNI',
  PASSEPORT: 'PASSEPORT'
};

const STATUT_VERIFICATION = {
  EN_ATTENTE: 'EN_ATTENTE',
  VERIFIE: 'VERIFIE',
  REJETE: 'REJETE'
};

const TYPE_CONVERSATION = {
  BAVARD: 'BAVARD',
  CALME: 'CALME',
  NEUTRE: 'NEUTRE'
};

const LANGUE_PREFEREE = {
  FRANCAIS: 'FR',
  ANGLAIS: 'ANG'
};

const RELATION_CONTACT_URGENCE = {
  FAMILLE: 'FAMILLE',
  AMI: 'AMI',
  COLLEGUE: 'COLLEGUE'
};

const BADGES_UTILISATEUR = {
  PONCTUEL: 'PONCTUEL',
  PROPRE: 'PROPRE',
  SYMPATHIQUE: 'SYMPATHIQUE',
  CONDUCTEUR_EXPERIMENTE: 'CONDUCTEUR_EXPERIMENTE',
  PASSAGER_IDEAL: 'PASSAGER_IDEAL',
  COMMUNICATIF: 'COMMUNICATIF',
  RESPECTUEUX: 'RESPECTUEUX'
};

const STATUT_COMPTE = {
  ACTIF: 'ACTIF',
  SUSPENDU: 'SUSPENDU',
  BLOQUE: 'BLOQUE',
  INACTIF: 'INACTIF'
};

// ========================================
// TRAJET - CONSTANTES
// ========================================

const TYPE_TRAJET = {
  PONCTUEL: 'PONCTUEL',
  RECURRENT: 'RECURRENT',
  EVENEMENTIEL: 'EVENEMENTIEL'
};

const JOURS_SEMAINE = {
  LUNDI: 'LUNDI',
  MARDI: 'MARDI',
  MERCREDI: 'MERCREDI',
  JEUDI: 'JEUDI',
  VENDREDI: 'VENDREDI',
  SAMEDI: 'SAMEDI',
  DIMANCHE: 'DIMANCHE'
};

const TYPE_BAGAGES = {
  PETIT: 'PETIT',
  MOYEN: 'MOYEN',
  GRAND: 'GRAND'
};

const STATUT_TRAJET = {
  PROGRAMME: 'PROGRAMME',
  EN_COURS: 'EN_COURS',
  TERMINE: 'TERMINE',
  ANNULE: 'ANNULE',
  SUSPENDU: 'SUSPENDU'
};

// ========================================
// RESERVATION - CONSTANTES
// ========================================

const STATUT_RESERVATION = {
  EN_ATTENTE: 'EN_ATTENTE',
  CONFIRMEE: 'CONFIRMEE',
  REFUSEE: 'REFUSEE',
  ANNULEE: 'ANNULEE',
  TERMINEE: 'TERMINEE'
};

const STATUT_PAIEMENT = {
  EN_ATTENTE: 'EN_ATTENTE',
  PAYE: 'PAYE',
  REMBOURSE: 'REMBOURSE',
  ECHEC: 'ECHEC'
};

const METHODE_PAIEMENT = {
  ESPECES: 'ESPECES',
  WAVE: 'WAVE',
  ORANGE_MONEY: 'ORANGE_MONEY',
  MTN_MONEY: 'MTN_MONEY',
  MOOV_MONEY: 'MOOV_MONEY'
};

const TYPE_NOTIFICATION = {
  RAPPEL_DEPART: 'RAPPEL_DEPART',
  CONDUCTEUR_PROCHE: 'CONDUCTEUR_PROCHE',
  ARRIVEE: 'ARRIVEE',
  RESERVATION_CONFIRMEE: 'RESERVATION_CONFIRMEE',
  RESERVATION_REFUSEE: 'RESERVATION_REFUSEE',
  TRAJET_ANNULE: 'TRAJET_ANNULE'
};

// ========================================
// MESSAGE - CONSTANTES
// ========================================

const TYPE_MESSAGE = {
  TEXTE: 'TEXTE',
  POSITION: 'POSITION',
  MODELE_PREDEFINI: 'MODELE_PREDEFINI',
  IMAGE: 'IMAGE',
  LOCALISATION: 'LOCALISATION'
};

const MODELES_MESSAGES_PREDEFINIS = {
  ARRIVEE_BIENTOT: "J'arrive bientôt au point de rendez-vous",
  RETARD_5MIN: "Je suis en retard de 5 minutes",
  RETARD_10MIN: "Je suis en retard de 10 minutes", 
  PROBLEME_CIRCULATION: "Il y a des embouteillages, je serai en retard",
  ARRIVE: "Je suis arrivé(e) au point de rendez-vous",
  DEMARRE: "On peut partir",
  MERCI_TRAJET: "Merci pour ce trajet !"
};

const TYPE_PIECE_JOINTE = {
  IMAGE: 'IMAGE',
  LOCALISATION: 'LOCALISATION'
};

// ========================================
// EVALUATION - CONSTANTES
// ========================================

const TYPE_EVALUATEUR = {
  CONDUCTEUR: 'CONDUCTEUR',
  PASSAGER: 'PASSAGER'
};

const ASPECTS_POSITIFS = {
  PONCTUEL: 'PONCTUEL',
  SYMPATHIQUE: 'SYMPATHIQUE',
  VEHICULE_PROPRE: 'VEHICULE_PROPRE',
  CONDUITE_SECURISEE: 'CONDUITE_SECURISEE',
  RESPECTUEUX: 'RESPECTUEUX',
  BON_COMMUNICANT: 'BON_COMMUNICANT',
  FLEXIBLE: 'FLEXIBLE'
};

const ASPECTS_A_AMELIORER = {
  PONCTUALITE: 'PONCTUALITE',
  PROPRETE: 'PROPRETE',
  CONDUITE: 'CONDUITE',
  COMMUNICATION: 'COMMUNICATION',
  RESPECT: 'RESPECT'
};

const GRAVITE_SIGNALEMENT = {
  LEGER: 'LEGER',
  MOYEN: 'MOYEN',
  GRAVE: 'GRAVE'
};

// ========================================
// EVENEMENT - CONSTANTES
// ========================================

const TYPE_EVENEMENT = {
  SPORT: 'SPORT',
  CONCERT: 'CONCERT',
  FESTIVAL: 'FESTIVAL',
  CONFERENCE: 'CONFERENCE',
  SALON: 'SALON',
  MARIAGE: 'MARIAGE',
  CEREMONIE: 'CEREMONIE'
};

const STATUT_EVENEMENT = {
  PROGRAMME: 'PROGRAMME',
  EN_COURS: 'EN_COURS',
  TERMINE: 'TERMINE',
  ANNULE: 'ANNULE'
};

const SOURCE_DETECTION = {
  MANUEL: 'MANUEL',
  AUTOMATIQUE: 'AUTOMATIQUE',
  API_EXTERNE: 'API_EXTERNE'
};

// ========================================
// ALERTE URGENCE - CONSTANTES
// ========================================

const TYPE_ALERTE = {
  SOS: 'SOS',
  ACCIDENT: 'ACCIDENT',
  AGRESSION: 'AGRESSION',
  PANNE: 'PANNE',
  MALAISE: 'MALAISE',
  AUTRE: 'AUTRE'
};

const NIVEAU_GRAVITE = {
  FAIBLE: 'FAIBLE',
  MOYEN: 'MOYEN',
  CRITIQUE: 'CRITIQUE'
};

const STATUT_ALERTE = {
  ACTIVE: 'ACTIVE',
  EN_TRAITEMENT: 'EN_TRAITEMENT',
  RESOLUE: 'RESOLUE',
  FAUSSE_ALERTE: 'FAUSSE_ALERTE'
};

const STATUT_NOTIFICATION_URGENCE = {
  ENVOYE: 'ENVOYE',
  RECU: 'RECU',
  ECHEC: 'ECHEC'
};

// ========================================
// PAIEMENT - CONSTANTES
// ========================================

const STATUT_PAIEMENT_DETAILLE = {
  EN_ATTENTE: 'EN_ATTENTE',
  TRAITE: 'TRAITE',
  COMPLETE: 'COMPLETE',
  ECHEC: 'ECHEC',
  REMBOURSE: 'REMBOURSE',
  ANNULE: 'ANNULE'
};

// ========================================
// ADMINISTRATEUR - CONSTANTES
// ========================================

const ROLE_ADMIN = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  MODERATEUR: 'MODERATEUR',
  SUPPORT: 'SUPPORT'
};

const PERMISSIONS = {
  ALL: 'ALL',
  GESTION_UTILISATEURS: 'GESTION_UTILISATEURS',
  MODERATION: 'MODERATION',
  ANALYTICS: 'ANALYTICS',
  GESTION_TRAJETS: 'GESTION_TRAJETS',
  GESTION_PAIEMENTS: 'GESTION_PAIEMENTS',
  SUPPORT_CLIENT: 'SUPPORT_CLIENT'
};

// ========================================
// SIGNALEMENT - CONSTANTES
// ========================================

const TYPE_SIGNALEMENT = {
  COMPORTEMENT: 'COMPORTEMENT',
  CONTENU: 'CONTENU',
  FRAUDE: 'FRAUDE',
  SECURITE: 'SECURITE',
  HARCELEMENT: 'HARCELEMENT',
  SPAM: 'SPAM'
};

const STATUT_TRAITEMENT = {
  EN_ATTENTE: 'EN_ATTENTE',
  EN_COURS: 'EN_COURS',
  TRAITE: 'TRAITE',
  REJETE: 'REJETE'
};

const ACTIONS_MODERATION = {
  AVERTISSEMENT: 'AVERTISSEMENT',
  SUSPENSION: 'SUSPENSION',
  BLOCAGE: 'BLOCAGE',
  SUPPRESSION_CONTENU: 'SUPPRESSION_CONTENU',
  AUCUNE_ACTION: 'AUCUNE_ACTION'
};

// ========================================
// VÉHICULE - CONSTANTES
// ========================================

const MARQUES_VEHICULES = {
  TOYOTA: 'TOYOTA',
  NISSAN: 'NISSAN',
  HYUNDAI: 'HYUNDAI',
  KIA: 'KIA',
  HONDA: 'HONDA',
  PEUGEOT: 'PEUGEOT',
  RENAULT: 'RENAULT',
  VOLKSWAGEN: 'VOLKSWAGEN',
  MERCEDES: 'MERCEDES',
  BMW: 'BMW',
  AUTRE: 'AUTRE'
};

const COULEURS_VEHICULES = {
  BLANC: 'BLANC',
  NOIR: 'NOIR',
  GRIS: 'GRIS',
  ROUGE: 'ROUGE',
  BLEU: 'BLEU',
  VERT: 'VERT',
  JAUNE: 'JAUNE',
  ORANGE: 'ORANGE',
  VIOLET: 'VIOLET',
  MARRON: 'MARRON'
};

// ========================================
// GÉOLOCALISATION - CONSTANTES
// ========================================

const COMMUNES_ABIDJAN = {
  ABOBO: 'ABOBO',
  ADJAME: 'ADJAME',
  ATTÉCOUBÉ: 'ATTÉCOUBÉ',
  COCODY: 'COCODY',
  KOUMASSI: 'KOUMASSI',
  MARCORY: 'MARCORY',
  PLATEAU: 'PLATEAU',
  PORT_BOUET: 'PORT_BOUET',
  TREICHVILLE: 'TREICHVILLE',
  YOPOUGON: 'YOPOUGON',
  BINGERVILLE: 'BINGERVILLE',
  SONGON: 'SONGON',
  ANYAMA: 'ANYAMA'
};

const VILLES_COTE_DIVOIRE = {
  ABIDJAN: 'ABIDJAN',
  BOUAKE: 'BOUAKE',
  DALOA: 'DALOA',
  YAMOUSSOUKRO: 'YAMOUSSOUKRO',
  KORHOGO: 'KORHOGO',
  SAN_PEDRO: 'SAN_PEDRO',
  MAN: 'MAN',
  GAGNOA: 'GAGNOA',
  DIVO: 'DIVO',
  ABENGOUROU: 'ABENGOUROU'
};

// ========================================
// VALIDATION - CONSTANTES
// ========================================

const REGEX_PATTERNS = {
  TELEPHONE_CI: /^(\+225|225)?[0-9]{8,10}$/,
  EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  IMMATRICULATION: /^[A-Z0-9]{2,10}$/,
  NUMERO_CNI: /^[0-9]{12}$/,
  NUMERO_PASSEPORT: /^[A-Z0-9]{6,9}$/
};

const LIMITES = {
  MIN_PLACES_VEHICULE: 1,
  MAX_PLACES_VEHICULE: 8,
  MIN_PRIX_TRAJET: 100, // FCFA
  MAX_PRIX_TRAJET: 50000, // FCFA
  MAX_DISTANCE_TRAJET: 1000, // km
  MIN_AGE_CONDUCTEUR: 18,
  MAX_AGE_UTILISATEUR: 80,
  MAX_CARACTERES_COMMENTAIRE: 500,
  MAX_TAILLE_PHOTO: 5 * 1024 * 1024, // 5MB
  MAX_CONTACTS_URGENCE: 3
};

// ========================================
// ERREURS - CONSTANTES
// ========================================

const CODES_ERREUR = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
};

const MESSAGES_ERREUR = {
  UTILISATEUR_NON_TROUVE: 'Utilisateur non trouvé',
  TRAJET_NON_TROUVE: 'Trajet non trouvé',
  RESERVATION_NON_TROUVE: 'Réservation non trouvée',
  EMAIL_EXISTE_DEJA: 'Un compte avec cet email existe déjà',
  TELEPHONE_EXISTE_DEJA: 'Un compte avec ce numéro de téléphone existe déjà',
  MOT_DE_PASSE_INCORRECT: 'Mot de passe incorrect',
  TOKEN_INVALIDE: 'Token d\'authentification invalide',
  ACCES_NON_AUTORISE: 'Accès non autorisé',
  PLACES_INSUFFISANTES: 'Nombre de places insuffisant',
  TRAJET_DEJA_COMMENCE: 'Ce trajet a déjà commencé',
  RESERVATION_DEJA_EXISTANTE: 'Une réservation existe déjà pour ce trajet'
};

// ========================================
// CONFIGURATION - CONSTANTES
// ========================================

const CONFIG = {
  JWT_EXPIRATION: '24h',
  BCRYPT_ROUNDS: 12,
  RATE_LIMIT_WINDOW: 15 * 60 * 1000, // 15 minutes
  RATE_LIMIT_MAX: 100, // requêtes par fenêtre
  PAGINATION_LIMIT_DEFAULT: 20,
  PAGINATION_LIMIT_MAX: 100,
  DISTANCE_RECHERCHE_DEFAULT: 10, // km
  TEMPS_LIMITE_CONFIRMATION: 30 * 60 * 1000, // 30 minutes
  DELAI_ANNULATION_GRATUITE: 2 * 60 * 60 * 1000 // 2 heures
};

// ========================================
// EXPORTS
// ========================================

module.exports = {
  // Utilisateur
  SEXE,
  TYPE_DOCUMENT_IDENTITE,
  STATUT_VERIFICATION,
  TYPE_CONVERSATION,
  LANGUE_PREFEREE,
  RELATION_CONTACT_URGENCE,
  BADGES_UTILISATEUR,
  STATUT_COMPTE,

  // Trajet
  TYPE_TRAJET,
  JOURS_SEMAINE,
  TYPE_BAGAGES,
  STATUT_TRAJET,

  // Réservation
  STATUT_RESERVATION,
  STATUT_PAIEMENT,
  METHODE_PAIEMENT,
  TYPE_NOTIFICATION,

  // Message
  TYPE_MESSAGE,
  MODELES_MESSAGES_PREDEFINIS,
  TYPE_PIECE_JOINTE,

  // Évaluation
  TYPE_EVALUATEUR,
  ASPECTS_POSITIFS,
  ASPECTS_A_AMELIORER,
  GRAVITE_SIGNALEMENT,

  // Événement
  TYPE_EVENEMENT,
  STATUT_EVENEMENT,
  SOURCE_DETECTION,

  // Alerte urgence
  TYPE_ALERTE,
  NIVEAU_GRAVITE,
  STATUT_ALERTE,
  STATUT_NOTIFICATION_URGENCE,

  // Paiement
  STATUT_PAIEMENT_DETAILLE,

  // Administration
  ROLE_ADMIN,
  PERMISSIONS,

  // Signalement
  TYPE_SIGNALEMENT,
  STATUT_TRAITEMENT,
  ACTIONS_MODERATION,

  // Véhicule
  MARQUES_VEHICULES,
  COULEURS_VEHICULES,

  // Géolocalisation
  COMMUNES_ABIDJAN,
  VILLES_COTE_DIVOIRE,

  // Validation
  REGEX_PATTERNS,
  LIMITES,

  // Erreurs
  CODES_ERREUR,
  MESSAGES_ERREUR,

  // Configuration
  CONFIG
};