// utils/errorCodes.js

module.exports = {
  // Auth/account status
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_TEMPORARILY_BLOCKED: 'ACCOUNT_TEMPORARILY_BLOCKED',
  ACCOUNT_PERMANENTLY_BLOCKED: 'ACCOUNT_PERMANENTLY_BLOCKED',
  ACCOUNT_PENDING_VERIFICATION: 'ACCOUNT_PENDING_VERIFICATION',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  SERVER_ERROR: 'SERVER_ERROR'
};


